# n8n
#
# n8n is an AI agent and workflow automation tool.
#
# https://n8n.io/
# https://docs.n8n.io/hosting/configuration/task-runners/

# Custom n8n docker-compose.yml file to add tracing, ffmpeg, etc.
include:
  - ./build/custom/docker-compose.yaml
#
# n8n standard version
# To switch back to unmodified version, uncomment the following section
# and comment out the include section above.
#
# volumes:
#   n8n_storage:
#
# x-n8n: &service-n8n
#   image: docker.n8n.io/n8nio/n8n:latest
#
#   environment:
#     # See https://docs.n8n.io/hosting/configuration/task-runners/
#     # Database used by n8n
#     - DB_TYPE=postgresdb
#     - DB_TABLE_PREFIX=n8n_
#     - DB_POSTGRESDB_HOST=${N8N_POSTGRES_HOST:-supavisor}
#     - DB_POSTGRESDB_USER=${N8N_POSTGRES_USER:-postgres}${POSTGRES_USER_TENANT_SUFFIX:-}
#     - DB_POSTGRESDB_PASSWORD=${N8N_POSTGRES_PASSWORD:-${POSTGRES_PASSWORD}}
#     - DB_POSTGRESDB_SCHEMA=${N8N_POSTGRES_SCHEMA:-public}
#     - DB_POSTGRESDB_DATABASE=postgres
#     - N8N_PERSONALIZATION_ENABLED=false
#     - N8N_ENCRYPTION_KEY
#     - N8N_USER_MANAGEMENT_JWT_SECRET
#     - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
#     - N8N_LOG_LEVEL=${N8N_LOG_LEVEL:-info}
#     - OLLAMA_HOST # set by start.ts as env var
#     # Deployment settings
#     # See https://docs.n8n.io/hosting/configuration/environment-variables/deployment/
#     - N8N_TEMPLATES_ENABLED=true
#     # Task runner settings
#     # See https://docs.n8n.io/hosting/configuration/task-runners/
#     - N8N_RUNNERS_ENABLED=true
#     # Disable sending diagnostics, notifications, and templates to n8n servers
#     # See https://docs.n8n.io/hosting/configuration/configuration-examples/isolation/
#     - N8N_DIAGNOSTICS_ENABLED=false
#     # - N8N_VERSION_NOTIFICATIONS_ENABLED=false
#     # - N8N_TEMPLATES_ENABLED=false
#     # - EXTERNAL_FRONTEND_HOOKS_URLS=
#     # - N8N_DIAGNOSTICS_CONFIG_FRONTEND=
#     # - N8N_DIAGNOSTICS_CONFIG_BACKEND=
# services:
#   n8n:
#     <<: *service-n8n
#     container_name: n8n
#     labels:
#       dev.dozzle.group: Workflows
#     restart: unless-stopped
#     ports:
#       - 5678:5678
#     volumes:
#       - n8n_storage:/home/node/.n8n
