networks:
  default:
    name: ${LLEMONSTACK_NETWORK_NAME}
    external: true

services:
  browser-use-webui:
    container_name: browser-use-webui
    labels:
      dev.dozzle.group: Browser Use
    platform: ${TARGETPLATFORM:-linux/amd64}
    extends:
      file: ${LLEMONSTACK_REPOS_PATH:-.}/browser-use-web-ui/docker-compose.yml
      service: browser-use-webui
    environment:
      # BROWSER_USE_* specific environment variables
      - CHROME_PERSISTENT_SESSION=${BROWSER_USE_CHROME_PERSISTENT_SESSION:-true}
      - RESOLUTION=${BROWSER_USE_RESOLUTION:-1920x1080x24}
      - RESOLUTION_WIDTH=${BROWSER_USE_RESOLUTION_WIDTH:-1920}
      - RESOLUTION_HEIGHT=${BROWSER_USE_RESOLUTION_HEIGHT:-1080}
      - VNC_PASSWORD=${BROWSER_USE_VNC_PASSWORD:-vncpassword}

      # LLM API Keys
      # If left blank, these can be set in the web UI at runtime
      - OPENAI_API_KEY=${BROWSER_USE_OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${BROWSER_USE_ANTHROPIC_API_KEY:-}
      - GOOGLE_API_KEY=${BROWSER_USE_GOOGLE_API_KEY:-}
      - DEEPSEEK_API_KEY=${BROWSER_USE_DEEPSEEK_API_KEY:-}

      - BROWSER_USE_LOGGING_LEVEL=${BROWSER_USE_LOGGING_LEVEL:-info}
      - ANONYMIZED_TELEMETRY=false
      # See additional configuration in the extended docker compose file
      # ${LLEMONSTACK_REPOS_PATH:-.}/browser-use-web-ui/docker-compose.yml

    healthcheck:
      test: wget -q -O- http://localhost:7788 | grep -qi 'browser use'
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
