# LiteLLM
#
# LiteLLM is a proxy for LLM providers.
#
# See:
# - https://github.com/BerriAI/litellm
# - https://docs.litellm.ai/

# LiteLLM requires a postgres database and prometheus.
# include:
#   - docker-compose.supabase.yml
#   # Prometheus is only available with LiteLLM Enterprise license
#   # - docker-compose.prometheus.yml

services:
  litellm:
    container_name: litellm
    image: ghcr.io/berriai/litellm:main-latest
    volumes:
      - ./config.litellm.yaml:/app/config.yaml
    command:
      - "--config=/app/config.yaml"
    ports:
      # Supabase Logflare uses port 4000
      - "3004:4000"
    environment:
      # Set log level: DEBUG | INFO | ERROR
      # See https://docs.litellm.ai/docs/proxy/debugging
      LITELLM_LOG: ${LITELLM_LOG_LEVEL:-INFO}
      # JSON_LOGS: "True"
      DATABASE_URL: ${LITELLM_DATABASE_URL}

      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY} # Key used by services to access litellm proxy
      LITELLM_SALT_KEY: ${LITELLM_SALT_KEY} # Salt key used to encrypt data in db
      UI_USERNAME: ${LITELLM_UI_USERNAME:-admin}
      UI_PASSWORD: ${LITELLM_UI_PASSWORD:-admin}

      OPENAI_API_KEY: ${LITELLM_OPENAI_API_KEY:-}
      ANTHROPIC_API_KEY: ${LITELLM_ANTHROPIC_API_KEY:-}
      GROQ_API_KEY: ${LITELLM_GROQ_API_KEY:-}

      # Langfuse settings
      LANGFUSE_HOST: http://langfuse:3000
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_INIT_PROJECT_PUBLIC_KEY:-}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_INIT_PROJECT_SECRET_KEY:-}

    # Only uncomment depends_on if include is uncommented above
    # depends_on:
    #   prometheus: # From docker-compose.prometheus.yml
    #     condition: service_healthy
    #   db: # From docker-compose.supabase.yml
    #     condition: service_healthy
