# LiteLLM
#
# LiteLLM is a proxy for LLM providers.
#
# See:
# - https://github.com/BerriAI/litellm
# - https://docs.litellm.ai/

# LiteLLM requires a postgres database and prometheus.
# include:
#   - docker-compose.supabase.yml
#   # Prometheus is only available with LiteLLM Enterprise license
#   # - docker-compose.prometheus.yml

services:
  litellm:
    container_name: litellm
    image: ghcr.io/berriai/litellm:main-stable
    volumes:
      - ./config.litellm.yaml:/app/config.yaml
    command:
      - "--config=/app/config.yaml"
    ports:
      # Supabase Logflare uses port 4000
      - "3004:4000"
    environment:
      # Set log level: DEBUG | INFO | ERROR
      # See https://docs.litellm.ai/docs/proxy/debugging
      LITELLM_LOG: ${LITELLM_LOG_LEVEL:-INFO}
      # JSON_LOGS: "True"

      DATABASE_URL: "postgresql://${LITELLM_POSTGRES_USER}:${LITELLM_POSTGRES_PASSWORD}@db:5432/${LITELLM_POSTGRES_DB}?schema=${LITELLM_POSTGRES_SCHEMA}"
      STORE_MODEL_IN_DB: "True" # allows adding models to proxy via UI

      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY} # Key used by services to access litellm proxy
      UI_USERNAME: ${LITELLM_UI_USERNAME:-admin}
      UI_PASSWORD: ${LITELLM_UI_PASSWORD:-admin}
      OPENAI_API_KEY: ${LITELLM_OPENAI_API_KEY:-}
      ANTHROPIC_API_KEY: ${LITELLM_ANTHROPIC_API_KEY:-}
      GROQ_API_KEY: ${LITELLM_GROQ_API_KEY:-}

      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_INIT_PROJECT_PUBLIC_KEY:-}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_INIT_PROJECT_SECRET_KEY:-}

    # Only uncomment depends_on if include is uncommented above
    # depends_on:
    #   prometheus: # From docker-compose.prometheus.yml
    #     condition: service_healthy
    #   db: # From docker-compose.supabase.yml
    #     condition: service_healthy
