# Flowise
#
# Flowise can run with a postgres database or a sqlite database.
# To switch to using sqlite as the default:
# - uncomment the flowise-standalone
# - comment out the flowise postgres service
# - comment out the include section
#
# https://docs.flowiseai.com/configuration/

# n8n requires a postgres database.
include:
  - ../.repos/supabase/docker/docker-compose.yml

volumes:
  flowise:


# Flowise with postgres database
x-flowise: &service-flowise
  image: flowiseai/flowise
  container_name: flowise
  restart: unless-stopped
  environment:
    # See https://docs.flowiseai.com/configuration/environment-variables
    - PORT=3001
    # Credentials, if blank auth is disabled
    # - FLOWISE_USERNAME=admin
    # - FLOWISE_PASSWORD=admin
    # Logging
    # - DEBUG=true
    # - LOG_LEVEL=debug # error, info, verbose, debug
    # - LOG_PATH=/Flowise/packages/server/logs
  ports:
    - 3001:3001
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    - flowise:/root/.flowise
  entrypoint: /bin/sh -c "sleep 3; flowise start"


services:
  # Flowise with postgres database: default
  flowise:
    <<: *service-flowise
    depends_on:
      db: # From supabase/docker/docker-compose.yml
        condition: service_healthy
    environment:
      # Database
      - DATABASE_TYPE=postgres # sqlite, postgres, mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_NAME=postgres
      - DATABASE_SSL=false

  # # Flowise with sqlite database: flowise-sqlite
  # flowise-standalone:
  #   <<: *service-flowise
  #   environment:
  #     # Database
  #     - DATABASE_TYPE=sqlite
