# Redis
#
# Redis is used by various services as a caching layer.
# Save to disk is disabled by default. Data in redis is ephemeral.
#
# https://github.com/redis/redis

services:
  redis:
    container_name: redis
    image: redis:7
    restart: always
    command: >
      --requirepass ${REDIS_PASSWORD} --loglevel warning
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 10
