# Flowise
#
# Flowise can run with a postgres database or a sqlite database.
# To switch to using sqlite as the default:
# - uncomment the sqlite database environment variable
# - comment out the postgres service
# - comment out the include section
# - comment out the depends_on section
#
# https://docs.flowiseai.com/configuration/

volumes:
  flowise:

# Flowise requires a postgres database.
# Comment this ection out if using sqlite database.
# include:
#   - docker-compose.supabase.yml

services:
  flowise:
    image: flowiseai/flowise
    container_name: flowise
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      # See https://docs.flowiseai.com/configuration/environment-variables
      - PORT=3001
      # Credentials, if blank auth is disabled
      - FLOWISE_USERNAME=${FLOWISE_USERNAME:-}
      - FLOWISE_PASSWORD=${FLOWISE_PASSWORD:-}
      # Logging
      # - DEBUG=true
      # - LOG_LEVEL=debug # error, info, verbose, debug
      # - LOG_PATH=/Flowise/packages/server/logs

      # Database - sqlite
      # - DATABASE_TYPE=sqlite

      # Database - supabase postgres
      - DATABASE_TYPE=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=${FLOWISE_POSTGRES_USER:-postgres}
      - DATABASE_PASSWORD=${FLOWISE_POSTGRES_PASSWORD:-${POSTGRES_PASSWORD}}
      - DATABASE_NAME=postgres
      - DATABASE_SSL=false

    # Supabase postgres database healthcheck
    # Comment this section out if using sqlite database.
    # Only uncomment depencency health check if include is uncommented above
    # depends_on:
    #   db: # From supabase/docker/docker/docker-compose.yml
    #     condition: service_healthy

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - flowise:/root/.flowise
    entrypoint: /bin/sh -c "sleep 3; flowise start"
