# Redis
#
# Redis is used by various services as a caching layer.
# By default, data is ephemeral and not saved to disk.
#
# https://github.com/redis/redis

volumes:
  redis_data:
    driver: local

services:
  redis:
    container_name: redis
    image: redis:7
    restart: always
    command: >
      --requirepass ${REDIS_PASSWORD} --loglevel warning
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 10
    volumes:
      - redis_data:/data
