# Standalone Services
#
# Services in this file do not have any external dependencies like supabase.
#
# Add additional services to the stack by adding them to this file.
# In general, if a service is published on Docker Hub and is self contained,
# it should be added to this file.
#
# For services that require custom builds, repos, or depend on other services
# in the stack, create a custom docker-compose.yml file and add it to the
# COMPOSE_FILES array in start.ts.

volumes:
  open-webui:
  qdrant_storage:
  flowise:

services:
  open-webui:
    profiles:
      - openwebui
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data

  qdrant:
    profiles:
      - qdrant
    image: qdrant/qdrant
    container_name: qdrant
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - qdrant_storage:/qdrant/storage

  flowise:
    profiles:
      - flowise
    image: flowiseai/flowise
    container_name: flowise
    restart: unless-stopped
    environment:
      # See https://docs.flowiseai.com/configuration/environment-variables
      - PORT=3001
    ports:
      - 3001:3001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - flowise:/root/.flowise
    entrypoint: /bin/sh -c "sleep 3; flowise start"
