# Flowise
#
# https://docs.flowiseai.com/configuration/

# Flowise requires a postgres database.
# Comment this ection out if using sqlite database.
# include:
#   - docker-compose.supabase.yml

services:
  flowise:
    container_name: flowise
    labels:
      dev.dozzle.group: Workflows
    image: flowiseai/flowise
    restart: unless-stopped
    ports:
      - 3001:3000
    environment:
      # See:
      # - https://docs.flowiseai.com/configuration/environment-variables
      # - https://github.com/FlowiseAI/Flowise/blob/main/docker/.env.example
      # - https://github.com/FlowiseAI/Flowise/tree/main/docker
      - PORT=3000

      # Credentials, if blank auth is disabled
      - FLOWISE_USERNAME=${FLOWISE_USERNAME:-}
      - FLOWISE_PASSWORD=${FLOWISE_PASSWORD:-}

      # Logging
      # - DEBUG=true
      # - LOG_LEVEL=debug # error, info, verbose, debug
      # - LOG_PATH=/Flowise/packages/server/logs

      # Database - supabase postgres
      - DATABASE_TYPE=postgres
      - DATABASE_HOST=${POSTGRES_HOST_INTERNAL:-supavisor}
      - DATABASE_PORT=5432
      - DATABASE_USER=${FLOWISE_POSTGRES_USER:-postgres}${POSTGRES_USER_TENANT_SUFFIX:-}
      - DATABASE_PASSWORD=${FLOWISE_POSTGRES_PASSWORD:-${POSTGRES_PASSWORD}}
      - DATABASE_NAME=postgres
      - DATABASE_SSL=false

      - APIKEY_STORAGE_TYPE=json # db | json
      - APIKEY_PATH=/root/.flowise/config

      - DISABLE_FLOWISE_TELEMETRY=true
      - STORAGE_TYPE=local # local | s3
      - BLOB_STORAGE_PATH=/root/.flowise

      - SECRETKEY_STORAGE_TYPE=local # local | aws
      - SECRETKEY_PATH=/root/.flowise/config

    extra_hosts:
      - "host.docker.internal:host-gateway"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    volumes:
      - ${LLEMONSTACK_VOLUMES_PATH:-../volumes}/flowise:/root/.flowise

    entrypoint: /bin/sh -c "sleep 3; flowise start"

    # Supabase postgres database healthcheck
    # Comment this section out if using sqlite database.
    # Only uncomment depencency health check if include is uncommented above
    # depends_on:
    #   db: # From docker-compose.supabase.yml
    #     condition: service_healthy
