version: 0.2.0 # Config file version

service: prometheus
name: Prometheus
description: Anlaytics database

compose_file: docker-compose.yaml
service_group: databases

provides:
  prometheus: prometheus # Name of the container

exposes:
  host:
    prometheus:
      name: Prometheus
      url: http://localhost:9090
