# Prometheus config
#
# See:
# - https://prometheus.io/
# - https://github.com/prometheus/prometheus

global:
  scrape_interval: 15s

scrape_configs:
  # LiteLLM
  # Only available with LiteLLM Enterprise license
  # - job_name: 'litellm'
  #   static_configs:
  #     - targets: ['litellm:4000']

