# Qdrant
#
# See https://qdrant.tech/documentation/

networks:
  default:
    name: ${LLEMONSTACK_NETWORK_NAME}
    external: true

volumes:
  qdrant_storage:

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    labels:
      dev.dozzle.group: Vector Stores
    restart: unless-stopped
    # environment:
    # See https://qdrant.tech/documentation/guides/configuration/
    # - QDRANT__SERVICE__API_KEY=123
    # - QDRANT__LOG_LEVEL=debug
    ports:
      - 6333:6333
    volumes:
      - qdrant_storage:/qdrant/storage
