# Minio
#
# Minio is a S3 compatible distributed object storage server.
# Used by Langfuse for storing traces.
#
# https://github.com/minio/minio

networks:
  default:
    name: ${LLEMONSTACK_NETWORK_NAME}
    external: true

services:
  minio:
    container_name: minio
    labels:
      dev.dozzle.group: Data Stores
    image: minio/minio
    restart: always
    entrypoint: sh
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9001:9000"
      - "9091:9001"
    # create the 'langfuse' bucket before starting the service
    command: -c 'mkdir -p /data/langfuse && minio server --address ":9000" --console-address ":9001" /data'
    volumes:
      - ${LLEMONSTACK_VOLUMES_PATH:-./volumes}/minio:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 1s
