# LightRAG

networks:
  default:
    name: ${LLEMONSTACK_NETWORK_NAME}
    external: true

services:
  lightrag:
    build:
      # Build from lightrag repo
      context: ${LLEMONSTACK_REPOS_PATH:-.}/lightrag
    container_name: lightrag
    labels:
      dev.dozzle.group: RAG
    ports:
      - "${LIGHTRAG_PORT:-9621}:9621"
    volumes:
      # rag_storage isn't used since we're using postgres for doc storage, but keeping it here for reference
      - ${LLEMONSTACK_VOLUMES_PATH:-./volumes}/lightrag/data:/app/data/rag_storage
      # inputs is the folder where incoming documents are stored and scanned for embedding
      - ${LLEMONSTACK_VOLUMES_PATH:-./volumes}/lightrag/inputs:/app/data/inputs
      - ./.env:/app/.env
      - ./healthcheck.py:/app/healthcheck.py
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "/app/healthcheck.py"]
      interval: 30s # Perform health check every 30 seconds
      timeout: 10s # Health check command times out after 10 seconds
      retries: 3 # Retry up to 3 times if health check fails
      start_period: 60s # Wait for container to start before beginning health checks
